version: '3.3'
services:
  app:
    container_name: docker-mongo
    restart: always
    build: .
    ports:
      - '80:3000'
    links:
      - mongo
      - mysql
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
      
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - "my_external_network"
volumes:
  mysql-data:
    driver: local
    
networks:
  my_external_network:
    external: true
      



